language: objective-c
osx_image: xcode11

install:
  - gem install xcpretty
  - sudo gem install cocoapods -v 1.8.0
  - pod --version
  - pod setup
  - pod update
  - pod install

script:
- xcodebuild clean build test -workspace ChainUtils.xcworkspace -scheme ChainUtils_Tests -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' -sdk iphonesimulator13.2 CODE_SIGNING_REQUIRED=NO -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES | xcpretty -c
- bash <(curl -s https://codecov.io/bash) -cF unit -J ChainUtils
- pod lib lint
